### PR TITLE
Authentication 

### PR DESCRIPTION
**Pull request by SukanyaSen530**
Components -
- InputFields with error messges
- Modal
- Modal Login & SignUp
- Protected Routes

Features -
- Login & SignUp for user
- Replaced mockbee api calls with backend
- Refactored - seperated the api calls into another file.
- Validations for Input fields 

PS : Initially I thought of creating the UI for auth cart and wishlist,  but later thought to complete authentication feature. So will change the branch name after merging.

### CODE REVIEW

**Review by sharathnair9999 — APPROVED** [review]

**Review by sharathnair9999 — APPROVED** [review]
Clean code. As usual. Good work.

**Review by Prabhav-Sharma — APPROVED** [review]
Suggestion: Add 'files to check' in PR description when the number of files changed is huge.
The code is clean and easy to navigate.

**Review by shashikantmaurya0007 — APPROVED** [review]
1.error on login page validation are getting reflected on sign-up page.  2.after logout user has access of authentication.3. ui is clean very well thought of  design

**Review by biswanath-tewari — APPROVED** [review]

**Comment by SukanyaSen530** [comment]
@shashikantmaurya0007 fixed the issues.

**Comment by shashikantmaurya0007** [comment]
> @shashikantmaurya0007 fixed the issues.

yes i can see it now.

**Pull request merged**
